# Site settings
title: 'Sharynne Azhar'
description: 'Collection of various coding notes, projects, thoughts.'
url: 'http://sharynneazhar.com/'
baseurl: '/blog/'
google_analytics: 'UA-91479922-2'
disqus_shortname: 'blog-sharynne-azhar'

author:
  name: 'Sharynne Azhar'
  email: sharynneazhar@gmail.com
  twitter_username: sharynneazhar
  instagram_username: heysharynne
  facebook_username:
  github_username:  sharynneazhar
  linkedin_username:  sharynneazhar

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
